apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-path-pv
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
